name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build and test PHP application
      run: |
        docker-compose -f docker-compose.yml up --build -d
        docker-compose exec php-apache php -v # Verifica si PHP está corriendo
        
    - name: Shut down containers after tests
      run: docker-compose down
